### ISSUE TITLE
To Tag a page is deleting the page in IE

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/tagging#6] opened 2014-12-09 14:47 UTC
I am using 2014-09-29b "Hrun" with the tagging-plugin. Disabled all other plugins to avoid incompatibility between plugins. To set a tag with IE 10 or 11 will delete the whole page. Works fine with Firefox.
![tagging1](https://cloud.githubusercontent.com/assets/2620833/5359035/9d473b38-7fba-11e4-8f88-9b1654e577f2.PNG)
![tagging2](https://cloud.githubusercontent.com/assets/2620833/5359036/9d56b662-7fba-11e4-895f-bc6a3cf0a012.PNG)
EDIT: I forgot to deactivate the recommend-plugin (https://github.com/cosmocode/recommend). The bug only appears with activated recommend-plugin. Should I report the issue there?

**Comment by splitbrain** [comment] 2017-09-06 07:36
probably duplicate of #39

**Closed by splitbrain** 2017-09-06 07:36 UTC
